"""redesign course chapter topic learning flow

Revision ID: 676fd60e37f4
Revises: 7014dd03d37b
Create Date: 2026-09-22 15:45:33.477173
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '676fd60e37f4'
down_revision: Union[str, Sequence[str], None] = '7014dd03d37b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    legacy_tables = ("skills", "skill_test_results", "student_skill_mastery")
    populated_legacy_tables = [
        table
        for table in legacy_tables
        if connection.execute(sa.text(f"SELECT COUNT(*) FROM {table}")).scalar_one() > 0
    ]
    if populated_legacy_tables:
        raise RuntimeError(
            "Legacy tables contain data and cannot be dropped automatically: "
            + ", ".join(populated_legacy_tables)
            + ". Export or migrate the data before upgrading."
        )

    op.execute("ALTER TYPE question_purpose RENAME VALUE 'test' TO 'chapter_final'")
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'order_index', name='uq_chapters_course_order')
    )
    op.create_table('course_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'course_id', name='uq_course_completions_user_course')
    )
    op.create_table('course_enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', name='enrollment_status'), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'course_id', name='uq_course_enrollments_user_course')
    )
    op.create_table('chapter_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('test_score_percent', sa.Float(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'chapter_id', name='uq_chapter_completions_user_chapter')
    )
    op.create_table('chapter_final_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('pass_percent', sa.Float(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chapter_id')
    )
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('general', 'grammar', 'listening', name='topic_type'), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('p_init', sa.Float(), nullable=False),
    sa.Column('p_transit', sa.Float(), nullable=False),
    sa.Column('p_slip', sa.Float(), nullable=False),
    sa.Column('p_guess', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chapter_id', 'order_index', name='uq_topics_chapter_order')
    )
    op.create_table('chapter_test_pools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['chapter_final_tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chapter_test_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('slot_index', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['chapter_final_tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_id', 'slot_index', name='uq_chapter_test_slots_test_order')
    )
    op.create_table('practice_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('questions_per_session', sa.Integer(), nullable=False),
    sa.Column('starting_level', sa.Integer(), nullable=False),
    sa.Column('level_1_questions', sa.Integer(), nullable=False),
    sa.Column('level_2_questions', sa.Integer(), nullable=False),
    sa.Column('level_3_questions', sa.Integer(), nullable=False),
    sa.Column('level_up_mastery', sa.Float(), nullable=False),
    sa.Column('completion_mastery', sa.Float(), nullable=False),
    sa.Column('review_mastery', sa.Float(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('review_limit', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id')
    )
    op.create_table('topic_mastery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('mastery', sa.Float(), nullable=False),
    sa.Column('current_level', sa.Integer(), nullable=False),
    sa.Column('practice_attempts', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'topic_id', name='uq_topic_mastery_user_topic')
    )
    op.create_table('chapter_test_slot_pools',
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pool_id'], ['chapter_test_pools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slot_id'], ['chapter_test_slots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('slot_id', 'pool_id')
    )
    op.create_table('chapter_test_pool_questions',
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pool_id'], ['chapter_test_pools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pool_id', 'question_id')
    )
    op.drop_constraint(op.f('lessons_skill_id_fkey'), 'lessons', type_='foreignkey')
    op.drop_constraint(op.f('stimuli_skill_id_fkey'), 'stimuli', type_='foreignkey')
    op.drop_constraint(op.f('questions_skill_id_fkey'), 'questions', type_='foreignkey')
    op.drop_constraint(op.f('attempts_skill_id_fkey'), 'attempts', type_='foreignkey')
    op.drop_constraint(op.f('learning_events_skill_id_fkey'), 'learning_events', type_='foreignkey')
    op.drop_constraint(op.f('recommendations_recommended_skill_id_fkey'), 'recommendations', type_='foreignkey')
    op.drop_table('skill_prerequisites')
    op.drop_table('skill_test_results')
    op.drop_table('student_skill_mastery')
    op.drop_table('skills')
    op.add_column('attempts', sa.Column('topic_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'attempts', 'topics', ['topic_id'], ['id'], ondelete='CASCADE')
    op.drop_column('attempts', 'skill_id')
    op.add_column('learning_events', sa.Column('topic_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'learning_events', 'topics', ['topic_id'], ['id'], ondelete='CASCADE')
    op.drop_column('learning_events', 'skill_id')
    op.add_column('lessons', sa.Column('topic_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'lessons', 'topics', ['topic_id'], ['id'], ondelete='CASCADE')
    op.drop_column('lessons', 'skill_id')
    op.add_column('questions', sa.Column('topic_id', sa.Integer(), nullable=False))
    op.add_column('questions', sa.Column('level', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'questions', 'topics', ['topic_id'], ['id'], ondelete='CASCADE')
    op.drop_column('questions', 'difficulty')
    op.drop_column('questions', 'skill_id')
    op.add_column('recommendations', sa.Column('topic_id', sa.Integer(), nullable=False))
    op.add_column('recommendations', sa.Column('recommended_level', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'recommendations', 'topics', ['topic_id'], ['id'], ondelete='CASCADE')
    op.drop_column('recommendations', 'recommended_difficulty')
    op.drop_column('recommendations', 'recommended_skill_id')
    op.add_column('stimuli', sa.Column('topic_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'stimuli', 'topics', ['topic_id'], ['id'], ondelete='CASCADE')
    op.drop_column('stimuli', 'skill_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stimuli', sa.Column('skill_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'stimuli', type_='foreignkey')
    op.create_foreign_key(op.f('stimuli_skill_id_fkey'), 'stimuli', 'skills', ['skill_id'], ['id'], ondelete='CASCADE')
    op.drop_column('stimuli', 'topic_id')
    op.add_column('recommendations', sa.Column('recommended_skill_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('recommendations', sa.Column('recommended_difficulty', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'recommendations', type_='foreignkey')
    op.create_foreign_key(op.f('recommendations_recommended_skill_id_fkey'), 'recommendations', 'skills', ['recommended_skill_id'], ['id'], ondelete='CASCADE')
    op.drop_column('recommendations', 'recommended_level')
    op.drop_column('recommendations', 'topic_id')
    op.add_column('questions', sa.Column('skill_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('questions', sa.Column('difficulty', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key(op.f('questions_skill_id_fkey'), 'questions', 'skills', ['skill_id'], ['id'], ondelete='CASCADE')
    op.drop_column('questions', 'level')
    op.drop_column('questions', 'topic_id')
    op.add_column('lessons', sa.Column('skill_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.create_foreign_key(op.f('lessons_skill_id_fkey'), 'lessons', 'skills', ['skill_id'], ['id'], ondelete='CASCADE')
    op.drop_column('lessons', 'topic_id')
    op.add_column('learning_events', sa.Column('skill_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'learning_events', type_='foreignkey')
    op.create_foreign_key(op.f('learning_events_skill_id_fkey'), 'learning_events', 'skills', ['skill_id'], ['id'], ondelete='CASCADE')
    op.drop_column('learning_events', 'topic_id')
    op.add_column('attempts', sa.Column('skill_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'attempts', type_='foreignkey')
    op.create_foreign_key(op.f('attempts_skill_id_fkey'), 'attempts', 'skills', ['skill_id'], ['id'], ondelete='CASCADE')
    op.drop_column('attempts', 'topic_id')
    op.create_table('student_skill_mastery',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('skill_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mastery', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('student_skill_mastery_skill_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('student_skill_mastery_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('student_skill_mastery_pkey')),
    sa.UniqueConstraint('user_id', 'skill_id', name=op.f('uq_student_skill_mastery_user_skill'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('skill_test_results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('skill_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('score_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('passed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('skill_test_results_skill_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('skill_test_results_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('skill_test_results_pkey')),
    sa.UniqueConstraint('user_id', 'skill_id', name=op.f('uq_skill_test_results_user_skill'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('skills',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', postgresql.ENUM('grammar', 'listening', name='skill_type'), autoincrement=False, nullable=False),
    sa.Column('p_init', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('p_transit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('p_slip', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('p_guess', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('skills_pkey'))
    )
    op.create_table('skill_prerequisites',
    sa.Column('skill_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('prerequisite_skill_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['prerequisite_skill_id'], ['skills.id'], name=op.f('skill_prerequisites_prerequisite_skill_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('skill_prerequisites_skill_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('skill_id', 'prerequisite_skill_id', name=op.f('skill_prerequisites_pkey'))
    )
    op.drop_table('chapter_test_pool_questions')
    op.drop_table('chapter_test_slot_pools')
    op.drop_table('topic_mastery')
    op.drop_table('practice_configurations')
    op.drop_table('chapter_test_slots')
    op.drop_table('chapter_test_pools')
    op.drop_table('topics')
    op.drop_table('chapter_final_tests')
    op.drop_table('chapter_completions')
    op.drop_table('course_enrollments')
    op.drop_table('course_completions')
    op.drop_table('chapters')
    op.drop_table('courses')
    # ### end Alembic commands ###
