"""add remedial source attempt foreign key

Revision ID: 7014dd03d37b
Revises: 064ef1848206
Create Date: 2026-09-19 15:51:20.551504
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7014dd03d37b'
down_revision: Union[str, Sequence[str], None] = '064ef1848206'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_questions_source_attempt_id', 'questions', 'attempts', ['source_attempt_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_questions_source_attempt_id', 'questions', type_='foreignkey')
    # ### end Alembic commands ###
